### PR TITLE
provide optional NTP support

### PR DESCRIPTION
**Pull request by trevharmon**
This PR adds NTP functionality to the module and the script it creates. This allows the administrator
the ability to have the script "temporarily" set NTP services to facilitate the installation of the Puppet
agent. It is expected once the Puppet agent has been installed, NTP services will be properly handled
by an NTP-specific module.

To maintain backward compatibility, this functionality is disabled by default, but can be enabled either
through node classification or via the command line.

### CODE REVIEW

**Comment by natemccurdy** [comment]
Thanks @trevharmon

I'll review this soon.

Also a couple notes:
- Don't worry too much about those gitmagic checks that are failing. I've got to tune those down some day.
- If you rebase off of `master` rather than merge, you won't get that merge commit and the commit history will be a bit cleaner.

**Comment by trevharmon** [comment]
Yeah, I should have rebased.

**Comment by acidprime** [comment]
I highly doubt most days NTP will be an issue on windows boxes as its typically handled by the fact that a node is joined to the domain.

**Comment by natemccurdy** [comment]
No new features will be added to this module as there is now native support for this in Puppet Enterprise. Closing this ticket.

**Pull request closed without merging**
